/* ----------------------------------------------------------------------------
 * Theme builder — maps each palette in src/themes.json onto the Facet token
 * contract and emits src/styles/themes.css. Run with: npm run build:themes
 *
 * The point of this script is the architecture it demonstrates: themes are
 * *data*, not hand-written CSS. A 16-colour terminal-style palette is enough
 * to drive the whole component library, because every component reads tokens.
 * -------------------------------------------------------------------------- */
import { readFileSync, writeFileSync } from 'node:fs'

const root = new URL('..', import.meta.url)
const themes = JSON.parse(readFileSync(new URL('src/themes.json', root), 'utf8'))

const rgba = (hex, a) => {
  const m = /^#?([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i.exec(hex || '')
  if (!m) return `rgba(127,127,127,${a})`
  const [r, g, b] = [1, 2, 3].map((i) => parseInt(m[i], 16))
  return `rgba(${r}, ${g}, ${b}, ${a})`
}

function tokens(c, dark) {
  const brand = c.accent || c.color4
  const brandStrong = c.color12 || c.color4 || brand
  const shadow = dark
    ? '0 1px 2px rgba(0,0,0,0.2), 0 18px 44px -14px rgba(0,0,0,0.55)'
    : '0 1px 2px rgba(16,24,40,0.03), 0 16px 40px -12px rgba(16,24,40,0.12)'
  return {
    '--ft-brand': brand,
    '--ft-brand-hover': c.color4 || brand,
    '--ft-brand-strong': brandStrong,
    '--ft-header-grad': `linear-gradient(135deg, ${brand} 0%, ${brandStrong} 100%)`,

    '--ft-success': c.color2,
    '--ft-success-hover': c.color2,
    '--ft-success-fg': c.color10 || c.color2,
    '--ft-success-bg': rgba(c.color2, 0.15),
    '--ft-success-line': rgba(c.color2, 0.32),
    '--ft-success-ring': rgba(c.color2, 0.28),

    '--ft-error': c.color1,
    '--ft-error-fg': c.color9 || c.color1,
    '--ft-error-bg': rgba(c.color1, 0.15),
    '--ft-error-line': rgba(c.color1, 0.32),

    '--ft-info': c.color4,
    '--ft-info-fg': c.color12 || c.color4,
    '--ft-info-bg': rgba(c.color4, 0.14),
    '--ft-info-line': rgba(c.color4, 0.32),

    '--ft-warn': c.color3,
    '--ft-warn-fg': c.color11 || c.color3,
    '--ft-warn-bg': rgba(c.color3, 0.16),
    '--ft-warn-line': rgba(c.color3, 0.4),

    '--ft-neutral-fg': c.color7 || c.foreground,
    '--ft-neutral-bg': rgba(c.color8 || c.color7, 0.18),
    '--ft-neutral-line': rgba(c.color8 || c.color7, 0.5),

    '--ft-surface-base': c.background,
    '--ft-surface-1': rgba(c.foreground, 0.05),
    '--ft-border': rgba(c.color8 || c.color7, 0.5),
    '--ft-text': c.foreground,
    '--ft-text-soft': c.color7 || rgba(c.foreground, 0.7),

    '--ft-btn-ghost-bg': c.background,
    '--ft-btn-ghost-fg': rgba(c.foreground, 0.74),
    '--ft-btn-ghost-line': rgba(c.color8 || c.foreground, 0.45),

    '--ft-kpi-total': brand,
    '--ft-kpi-total-ring': rgba(brand, 0.25),
    '--ft-kpi-volume': c.color2,
    '--ft-kpi-volume-ring': rgba(c.color2, 0.25),
    '--ft-kpi-accent': c.color6 || c.color4,
    '--ft-kpi-accent-ring': rgba(c.color6 || c.color4, 0.25),
    '--ft-kpi-pending': c.color3,
    '--ft-kpi-pending-ring': rgba(c.color3, 0.25),
    '--ft-kpi-error': c.color1,
    '--ft-kpi-error-ring': rgba(c.color1, 0.25),

    '--ft-chip-ok-bg': rgba(c.color2, 0.15), '--ft-chip-ok-fg': c.color10 || c.color2, '--ft-chip-ok-line': rgba(c.color2, 0.32),
    '--ft-chip-err-bg': rgba(c.color1, 0.15), '--ft-chip-err-fg': c.color9 || c.color1, '--ft-chip-err-line': rgba(c.color1, 0.32),
    '--ft-chip-blue-bg': rgba(c.color4, 0.14), '--ft-chip-blue-fg': c.color12 || c.color4, '--ft-chip-blue-line': rgba(c.color4, 0.32),
    '--ft-chip-grey-bg': rgba(c.color8 || c.color7, 0.16), '--ft-chip-grey-fg': c.color7 || c.foreground, '--ft-chip-grey-line': rgba(c.color8 || c.color7, 0.4),

    '--ft-card-shadow': shadow,
  }
}

const block = (sel, map) =>
  `${sel} {\n` +
  Object.entries(map).map(([k, v]) => `  ${k}: ${v};`).join('\n') +
  `\n}\n`

let out =
  `/* GENERATED by scripts/build-themes.mjs from src/themes.json — do not edit by hand.\n` +
  ` * ${themes.length} theme presets. Apply with <html data-theme="tokyo-night">. */\n\n`

out += themes.map((t) => block(`[data-theme='${t.name}']`, tokens(t.colors, t.dark))).join('\n')

writeFileSync(new URL('src/styles/themes.css', root), out)
console.log(`Built ${themes.length} themes -> src/styles/themes.css`)
